apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tc-webui
  name: tc-webui-pvc
  namespace: tc-webui
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi